name: Nightly Test run

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  integration-tests-standalone:
    name: Integration Tests (Standalone)
    strategy:
      fail-fast: false
      matrix:
        jahia_image: ["jahia/jahia-ee:8", "ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT"]
    secrets: inherit
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    with:
      module_id: app-shell
      testrail_project: App Shell Module
      jahia_image: ${{ matrix.jahia_image }}
      incident_service: app-shell-${{ matrix.jahia_image }}
      provisioning_manifest: provisioning-manifest-snapshot.yml
      artifact_prefix: app-shell-artifacts
      timeout_job: 45
