# This workflow is triggered every time a change is pushed to any branches
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On merge to main

# The workflow could also be triggered on PRs
on:
  push:
    branches:
      - 'main'
      - '/[0-9]_[0-9]_[Xx]/'
    tags-ignore:
      - '**'

jobs:
  update-signature:
    name: Update module signature
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jahia/jahia-modules-action/update-signature@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}

  build:
    name: Build Module
    needs: update-signature
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jahia/jahia-docker-mvn-cache:8-jdk-noble-mvn-loaded
      credentials:
        username: ${{ secrets.GH_PACKAGES_USERNAME }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: jahia/jahia-modules-action/build@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          
  sbom:
    name: SBOM processing
    needs: build
    runs-on: ubuntu-latest
    container:
      image: cyclonedx/cyclonedx-cli:0.24.2   
    steps:
      - uses: jahia/jahia-modules-action/sbom-processing@v2
        with:
          dependencytrack_hostname: ${{ vars.DEPENDENCYTRACK_HOSTNAME }}
          dependencytrack_apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          sbom_artifacts: 'build-artifacts'
          
  integration-tests-standalone:
    name: Integration Tests (Standalone)
    needs: build
    secrets: inherit
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    with:
      module_id: app-shell
      testrail_project: App Shell Module
      incident_service: app-shell-ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT
      jahia_image: ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT
      provisioning_manifest: provisioning-manifest-build.yml
      artifact_prefix: app-shell-artifacts
      timeout_job: 45

  publish:
    name: Publish module
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jahia/jahia-docker-mvn-cache:8-jdk-noble-mvn-loaded
      credentials:
        username: ${{ secrets.GH_PACKAGES_USERNAME }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: jahia/jahia-modules-action/publish@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
